# Generated by Django 4.0.4 on 2022-05-16 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aadhar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('blood_grp', models.CharField(max_length=3)),
                ('aadhar', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aadhar.aadhar')),
            ],
        ),
        migrations.CreateModel(
            name='JobExp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comp_name', models.TextField()),
                ('role', models.TextField()),
                ('work_exp', models.PositiveIntegerField()),
                ('aadhar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aadhar.aadhar')),
            ],
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('per', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aadhar.personaldetails')),
            ],
        ),
        migrations.CreateModel(
            name='ContactNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveBigIntegerField(max_length=11)),
                ('per', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aadhar.personaldetails')),
            ],
        ),
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acc_no', models.CharField(max_length=20)),
                ('bank_name', models.TextField()),
                ('ifsc', models.CharField(max_length=11)),
                ('aadhar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aadhar.aadhar')),
            ],
        ),
    ]
