# Generated by Django 4.0.4 on 2022-05-16 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aadhar', '0002_personaldetails_jobexp_email_contactnumber_bank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactnumber',
            name='number',
            field=models.PositiveBigIntegerField(),
        ),
    ]
