# Generated by Django 4.0.4 on 2022-05-16 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aadhar', '0003_alter_contactnumber_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aadhar', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='aadhar.aadhar')),
                ('address', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='aadhar.address')),
                ('bank', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='aadhar.bank')),
                ('jobexp', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='aadhar.jobexp')),
                ('perdet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='aadhar.personaldetails')),
                ('quali', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='aadhar.qualification')),
            ],
        ),
    ]
