# Generated by Django 4.0.4 on 2022-05-16 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='aadhar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.aadhar'),
        ),
        migrations.AddField(
            model_name='qualification',
            name='aadhar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.aadhar'),
        ),
        migrations.AlterField(
            model_name='aadhar',
            name='aadhar_no',
            field=models.CharField(max_length=12, primary_key=True, serialize=False),
        ),
    ]
