# Generated by Django 4.0.4 on 2022-05-16 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_address_aadhar_qualification_aadhar_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='aadhar',
        ),
        migrations.RemoveField(
            model_name='qualification',
            name='aadhar',
        ),
        migrations.DeleteModel(
            name='Aadhar',
        ),
        migrations.DeleteModel(
            name='Address',
        ),
        migrations.DeleteModel(
            name='Qualification',
        ),
    ]
